views:
  side:
    prefix: '1_'
    suffix: '_side'
    zoom_factor: 0.7
    rotate: '315,360,405'
    pan: '0,0.6,0'
    light_elevation: 30
    side: 'top'  # (top, bottom, left, right, front, back)
    hide_footprints:
      - M1
      - M2
      - M3
    
  top:
    prefix: '2_'
    suffix: '_top'
    zoom_factor: 0.7
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'top'
    
  bottom:
    prefix: '3_'
    suffix: '_bottom'
    zoom_factor: 0.7
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'bottom'
    
  left:
    prefix: '4_'
    suffix: '_left'
    zoom_factor: 1.4
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 10
    side: 'left'
    
  right:
    prefix: '5_'
    suffix: '_right'
    zoom_factor: 1.4
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 10
    side: 'right'
    
  front:
    prefix: '6_'
    suffix: '_front'
    zoom_factor: 1.4
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 10
    side: 'front'
    
  back:
    prefix: '7_'
    suffix: '_back'
    zoom_factor: 1.4
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 10
    side: 'back'

  side_exploded_1:
    prefix: '8_'
    suffix: '_side_exploded_1'
    zoom_factor: 0.45
    rotate: '315,360,405'
    pan: '0,-3,0'
    light_elevation: 30
    side: 'top'
    show_footprints:
      - M1
      - M2
      - M3
    hide_footprints:
      - MOD1
      - MOD2
      - MOD3
      - MOD4
      - MOD5
      - MOD6
    offset_footprints:
      - reference: M1
        x: -40
        y: 0
        z: 0
      - reference: M2
        x: 120
        y: 0
        z: 0
      - reference: M3
        x: 160
        y: 0
        z: 0

defaults:
  zoom_factor: 1.0
  rotate: '0,0,0'
  pan: '0,0,0'
  light_elevation: 60
  side: 'top'
